pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building docker image..'
                sh "docker build -t semyonov4360/flask_endpoint ./flask_service"
    //          Next step is to push this image to semyonov docker-hub repo
                //Jenkins will require credentials to get into this repo

                withCredentials([[$class: 'UsernamePasswordMultiBinding',
                credentialsId: 'docker-hub-credentials',
                usernameVariable: 'DOCKER_HUB_USER',
                passwordVariable: 'DOCKER_HUB_PASSWORD']])
                {
                    sh "docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWORD}"
                }

                //**Now push to semyonov4360 repo
                sh "docker push semyonov4360/flask_endpoint"

            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                echo 'Flask Endpoint needs TDD'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                sh "docker rm flask_endpoint --force"
                sh "docker run --name flask_endpoint -p 7904:5000 semyonov4360/flask_endpoint"
            }
        }
    }
}
